import React, { useState } from "react";
import { useParams, useNavigate } from "react-router-dom";
import { quizService } from "../services/quizService";
import Navbar from "../components/Navbar";

export default function ImportAiQuiz() {
  const { quizId } = useParams();
  const navigate = useNavigate();

  const [jsonText, setJsonText] = useState("");
  const [error, setError] = useState("");
  const [statusMessage, setStatusMessage] = useState("");
  const [loading, setLoading] = useState(false);

  const handleImport = async (e) => {
    e.preventDefault();
    if (!jsonText.trim()) return;

    if (!quizId) {
      setError("No Quiz ID found for import. Please start from Create Quiz.");
      return;
    }

    setError("");
    setLoading(true);
    setStatusMessage("Validating JSON syntax...");

    let payload;
    try {
      payload = JSON.parse(jsonText);
    } catch (parseErr) {
      setError("Invalid JSON format: " + parseErr.message);
      setLoading(false);
      return;
    }

    try {
      setStatusMessage("Importing questions into Django backend...");
      await quizService.importAIQuiz(quizId, payload);
      setStatusMessage("Quiz generated successfully! Redirecting to preview...");

      setTimeout(() => {
        navigate(`/staff/quiz/${quizId}/preview`);
      }, 800);
    } catch (apiErr) {
      console.error("[ImportAiQuiz] Error importing AI JSON:", apiErr);
      setError(apiErr.message || "Failed to import AI specification to Django backend.");
      setLoading(false);
    }
  };

  return (
    <div className="app-shell">
      <Navbar />
      <main className="app-content container" style={{ maxWidth: "800px" }}>
        <button
          className="btn btn-ghost btn-sm"
          onClick={() => navigate(`/staff/quiz/${quizId}/terminal`)}
          style={{ marginBottom: "16px" }}
          disabled={loading}
        >
          ← Back to AI Specification Terminal
        </button>

        <div style={{ marginBottom: "20px" }}>
          <div style={{ display: "flex", alignItems: "center", gap: "8px", marginBottom: "4px" }}>
            <span className="badge badge-accent">External AI Importer</span>
            {quizId && <span className="badge badge-neutral">Quiz #{quizId}</span>}
          </div>
          <h1 style={{ fontSize: "28px" }}>Import Assessment Specification</h1>
          <p style={{ color: "var(--color-text-secondary)", fontSize: "14px" }}>
            Paste the raw JSON output generated by ChatGPT, Claude, or Gemini to populate quiz questions.
          </p>
        </div>

        {error && <div className="form-error" style={{ marginBottom: "16px" }}>{error}</div>}

        <div className="card" style={{ padding: "28px 32px" }}>
          {loading ? (
            <div style={{ textAlign: "center", padding: "36px" }}>
              <div className="pulse-dot" style={{ margin: "0 auto 16px" }} />
              <p style={{ color: "var(--color-accent)", fontFamily: "var(--font-mono)", fontSize: "15px" }}>
                {statusMessage}
              </p>
            </div>
          ) : (
            <form onSubmit={handleImport}>
              <div className="form-group">
                <label className="label">JSON Specification Payload *</label>
                <textarea
                  className="json-input"
                  rows={14}
                  value={jsonText}
                  onChange={(e) => {
                    setJsonText(e.target.value);
                    setError("");
                  }}
                  placeholder='Paste JSON schema here e.g. { "questions": [ { "question_text": "...", "option_a": "...", ... } ] }'
                  required
                  style={{ fontFamily: "var(--font-mono)", fontSize: "13px" }}
                  autoFocus
                />
              </div>
              <div style={{ display: "flex", justifyContent: "flex-end", gap: "12px", marginTop: "16px" }}>
                <button
                  type="button"
                  className="btn btn-secondary btn-md"
                  onClick={() => navigate("/staff/dashboard")}
                >
                  Cancel
                </button>
                <button type="submit" className="btn btn-primary btn-md" disabled={loading}>
                  Import Questions & Preview →
                </button>
              </div>
            </form>
          )}
        </div>
      </main>
    </div>
  );
}
